#!/bin/bash

export NODE_PRIORITIZED_PATH=/usr/lib/node_modules

while true; do
  /usr/bin/iotjs /usr/lib/yoda/ota/index.js
  status=$?
  printf "OTA exited for code $status\n"
  if test $status = 0; then
    sleep 1800
  else
    r=$(($RANDOM%30))
    printf "sleeping for ${r}s\n"
    sleep "${r}"
  fi
done
