#!/bin/bash

export NODE_PRIORITIZED_PATH=/usr/lib/node_modules

while true; do
  /usr/bin/iotjs /usr/yoda/services/otad/index.js &
  PID=$!
  countdown=1800
  remaining=0
  while test $countdown != 0; do
    res=$(ps | grep "$PID")
    printf "[DEBUG] $res"
    if test -z "$res"; then
      # ota exits
      remaining=$countdown
      countdown=0
    else
      # ota still running
      countdown=$(expr $countdown - 30)
      sleep 30
    fi
  done

  res=$(ps | grep "$PID")
  if test -z "$res"; then
    # inform otad that it's time to pause
    kill -SIGINT $PID
  fi

  wait $PID
  status=$?
  printf "OTA exited for code $status\n"
  if test $status = 0; then
    sleep $remaining
  else
    r=$(($RANDOM%30))
    printf "sleeping for ${r}s\n"
    sleep "${r}"
  fi
done
