#!/usr/bin/env bash
set -e

help="
Usage:
  -t Only includes tests.
  -a Include tests.
  -s serial number.

Runtime installation by default, includes all packages, runtime, **no tests**.

Example:
  $ ./tools/runtime-install
"

os="YES"
test="NO"
sn=""

while [ $# -gt 0 ]; do
  case "$1" in
    -t)
      test="YES"
      os="NO"
      ;;
    -a)
      test="YES"
      ;;
    -s)
      sn="$2"
      shift
      ;;
    -h|--help)
      printf "$help"
      exit
      ;;
    --*)
      echo "Illegal option $1"
      ;;
  esac
  shift $(( $# > 0 ? 1 : 0 ))
done

function shell() {
  if test "$sn" != ""; then
    adb -s "$sn" shell $1
  else
    adb shell $1
  fi
}

function push() {
  echo "installing from $1 to $2"
  if test "$sn" != ""; then
    adb -s "$sn" push $1 $2 >/dev/null
  else
    adb push $1 $2 >/dev/null
  fi
}

function install_os() {
  shell "mount -o remount,rw /"
  shell "rm -rf /usr/lib/yoda/runtime"
  push "./runtime" "/usr/lib/yoda/"

  # apps
  shell "rm -rf /opt/apps/*"
  push "./apps/*" "/opt/apps/"

  # resource
  shell "rm -rf /opt/media"
  shell "rm -rf /opt/light"
  push "./res/light" "/opt/"
  push "./res/media" "/opt/"

  # node_modules
  shell "mkdir -p /usr/lib/node_modules/@yoda"
  push "packages/*" "/usr/lib/node_modules"
}

function install_test() {
  shell "rm -rf /data/workspace/test"
  shell "mkdir -p /data/workspace/test"
  push "test/*" "/data/workspace/test"
}

if test "$os" = "YES"; then
  install_os
fi

if test "$test" = 'YES'; then
  install_test
fi
