#!/usr/bin/env bash
set -e

help="
Example:
  $ ./tools/send-asr '你吼啊'
"

asr=''
verbose=''
while [ $# -gt 0 ]; do
  case "$1" in
    --verbose)
      verbose='YES'
      ;;
    --help)
      printf "$help"
      exit
      ;;
    -h)
      printf "$help"
      exit
      ;;
    -*)
      echo "Illegal option $1"
      ;;
    *)
      asr="$1"
      ;;
  esac
  shift $(( $# > 0 ? 1 : 0 ))
done

adb shell "mount -o remount,rw /"
adb shell mkdir -p /data/workspace/helper/ >/dev/null
adb push ./tools/helper/send-asr.js /data/workspace/helper/ >/dev/null
adb shell "iotjs /data/workspace/helper/send-asr.js '$asr' $verbose"
