#!/usr/bin/env bash
set -e

help="
Example:
  $ ./tools/yoda-debug GetLifetime

Available debug methods:
"

iface=''
while [ $# -gt 0 ]; do
  case "$1" in
    --help)
      printf "$help"
      iface='--help'
      ;;
    -h)
      printf "$help"
      iface='--help'
      ;;
    -*)
      echo "Illegal option $1"
      ;;
    *)
      iface="$1"
      ;;
  esac
  shift $(( $# > 0 ? 1 : 0 ))
done

adb shell "mount -o remount,rw /"
adb shell mkdir -p /data/workspace/helper/ >/dev/null
adb push ./tools/helper/yoda-debug.js /data/workspace/helper/ >/dev/null
adb shell "iotjs /data/workspace/helper/yoda-debug.js '$iface'"
