/**
* @file  yodaos_api_container.h  
* @brief The container of event information and api information. This file is automatically generated, please do not modify it directly.
*/
#include "yodaos_api_defines.h"
#include "yodaos_apis.h"

/**
 * @brief the method container,include namespace and method name.
 */
struct yodaos_api_s api_container[] = {
    {YODAOSAPI_NS_AUDIOFOCUS_MT_REQUEST, "audioFocus", "request"},
    {YODAOSAPI_NS_AUDIOFOCUS_MT_ABANDON, "audioFocus", "abandon"},
    {YODAOSAPI_NS_AUDIOFOCUS_MT_GETCURRENTFOCUSES, "audioFocus", "getCurrentFocuses"},
    {YODAOSAPI_NS_BROADCAST_MT_REGISTERBROADCAST, "broadcast", "registerBroadcast"},
    {YODAOSAPI_NS_BROADCAST_MT_UNREGISTERBROADCAST, "broadcast", "unregisterBroadcast"},
    {YODAOSAPI_NS_CHRONOS_MT_SCHEDULE, "chronos", "schedule"},
    {YODAOSAPI_NS_CHRONOS_MT_CANCEL, "chronos", "cancel"},
    {YODAOSAPI_NS_EFFECT_MT_PLAY, "effect", "play"},
    {YODAOSAPI_NS_EFFECT_MT_STOP, "effect", "stop"},
    {YODAOSAPI_NS_KEYBOARD_MT_PREVENTDEFAULTS, "keyboard", "preventDefaults"},
    {YODAOSAPI_NS_KEYBOARD_MT_RESTOREDEFAULTS, "keyboard", "restoreDefaults"},
    {YODAOSAPI_NS_KEYBOARD_MT_RESTOREALL, "keyboard", "restoreAll"},
    {YODAOSAPI_NS_RUNTIME_MT_SETPHASE, "runtime", "setPhase"},
    {YODAOSAPI_NS_VISIBILITY_MT_GETKEYANDVISIBLEAPPID, "visibility", "getKeyAndVisibleAppId"},
    {YODAOSAPI_NS_VISIBILITY_MT_ABANDONKEYVISIBILITY, "visibility", "abandonKeyVisibility"},
    {YODAOSAPI_NS_VISIBILITY_MT_ABANDONALLVISIBILITIES, "visibility", "abandonAllVisibilities"},
    {YODAOSAPI_NS_GLOBAL_MT_EXIT, "", "exit"},
    {YODAOSAPI_NS_GLOBAL_MT_OPENURL, "", "openUrl"},
    {YODAOSAPI_NS_GLOBAL_MT_SETCONTEXTOPTIONS, "", "setContextOptions"},
    {YODAOSAPI_NS_GLOBAL_MT_GETCONTEXTOPTIONS, "", "getContextOptions"},
    {YODAOSAPI_NS_GLOBAL_MT_STARTMONOLOGUE, "", "startMonologue"},
    {YODAOSAPI_NS_GLOBAL_MT_STOPMONOLOGUE, "", "stopMonologue"},
};
/**
* @brief the event container,include namespace and event name.
*/
struct yodaos_ev_s ev_container[] = {
    {YODAOSAPI_NS_AUDIOFOCUS_EV_GAIN, "audioFocus", "gain"},
    {YODAOSAPI_NS_AUDIOFOCUS_EV_LOSS, "audioFocus", "loss"},
    {YODAOSAPI_NS_BROADCAST_EV_BROADCAST, "broadcast", "broadcast"},
    {YODAOSAPI_NS_KEYBOARD_EV_KEYDOWN, "keyboard", "keydown"},
    {YODAOSAPI_NS_KEYBOARD_EV_KEYUP, "keyboard", "keyup"},
    {YODAOSAPI_NS_KEYBOARD_EV_CLICK, "keyboard", "click"},
    {YODAOSAPI_NS_KEYBOARD_EV_DBLCLICK, "keyboard", "dblclick"},
    {YODAOSAPI_NS_KEYBOARD_EV_LONGPRESS, "keyboard", "longpress"},
    {YODAOSAPI_NS_GLOBAL_EV_CREATED, "", "created"},
    {YODAOSAPI_NS_GLOBAL_EV_PAUSED, "", "paused"},
    {YODAOSAPI_NS_GLOBAL_EV_RESUMED, "", "resumed"},
    {YODAOSAPI_NS_GLOBAL_EV_DESTROYED, "", "destroyed"},
    {YODAOSAPI_NS_GLOBAL_EV_URL, "", "url"},
    {YODAOSAPI_NS_GLOBAL_EV_OPPRESSING, "", "oppressing"},
};